name: Install build prerequisites
description: Reusable action to set up build prerequisites

runs:
  using: "composite"
  steps:
    - name: Install build prerequisites
      shell: bash
      run: apk add clang oniguruma-dev

    - name: Ensure onig_sys uses libonig
      shell: bash
      run: echo "RUSTONIG_SYSTEM_LIBONIG=1" >> "${GITHUB_ENV}"
