[package]
name = "cargo-spellcheck-demo-inner"
publish = false
description = "Inner member of the demo"
readme = "README.md"

version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["staticlib"]
path = "lib.rs"
bench = false
test = false


[dependencies]
